try {
    // Code that might throw an error
    let result = potentiallyFailingFunction();
    console.log(result);
} catch (e) {
    // Error is caught but nothing is done with it
    // In this example, we are ignoring the error
}
